### ISSUE TITLE
ForEach usage?

### ISSUE THREAD

**Issue by joyrexus** [djherbis/stow#1]
Looks nice!

Could you perhaps provide an example of using [Store.ForEach](https://github.com/djherbis/stow/blob/master/store.go#L117-L118)?  I gather one could use this as an efficient way to retrieve a list of items.

**Comment by joyrexus** [comment]
[Easy enough](https://gist.github.com/joyrexus/d799527b7b3762784b35#file-demo-go-L49-L53).  Perhaps worth mentioning in the README or having an example in the tests.

**Comment by djherbis** [comment]
Hey I actually slightly changed how ForEach works. I've updated the test file with an example. I'm working on adding more documentation to this repo.
