### ISSUE TITLE
Type registration when using NewStore?

### ISSUE THREAD

**Issue by joyrexus** [djherbis/stow#2]
Gob complains if you don't [register](https://gist.github.com/joyrexus/d799527b7b3762784b35#file-demo-go-L18) the types you want to stow when using `stow.NewStore`:

    gob: type not registered for interface: MyType

Any way around this?

**Comment by djherbis** [comment]
Unfortunately I don't know a way of getting around not-registering the type. However, my suggestions is that you just register a type in the same package that you create it in, using the special init() function. 

```go
type Mytype struct{}

func init(){
    gob.Register(MyType{})
}
```

**Comment by joyrexus** [comment]
What if [NewStore](https://github.com/djherbis/stow/blob/master/store.go#L27) took the type-to-be-registered as a third arg and did the registration for you?

```go
    func NewStore(db *bolt.DB, bucket []byte, toType interface{}) *Store {
        gob.Register(toType)
        ...
```

I'll submit a pull request if you're cool with this.

**Comment by djherbis** [comment]
You can store any number of types in a store, it's not limited to a particular one. So you can't really register it when you create the store.

**Comment by joyrexus** [comment]
How 'bout ...

```go
func NewStore(db *bolt.DB, bucket []byte, toTypes... interface{}) *Store {
    for _, t := range toTypes {
        gob.Register(t)
    }
```

**Comment by djherbis** [comment]
Out of curiosity, is there any reason you don't like the solution where you register it in the init() section? Register only needs to be done once for a type (it would be redundant to call it it again for a second store).

**Comment by joyrexus** [comment]
Yeah, it feels odd to me to have to import package X (viz., `encoding/gob`) and then do something with X for the sake of another imported package Y, instead of doing it through Y's API.

**Comment by djherbis** [comment]
If importing is the problem, I could add a Register method so you don't have to import encoding/gob. Would that suffice?

**Comment by joyrexus** [comment]
Yeah, that'd work.  Thanks!

**Comment by djherbis** [comment]
stow.Register is now an alias for gob.Register, thanks for your input!
