### ISSUE TITLE
Server based connection pooling

### ISSUE THREAD

**Issue by joeblew99** [djherbis/stow#3]
This looks good.

I need to use this with a http server in front though.
I read that boltdb is only designed for embedded, so m wondering if there is a decent way to polll connection that maintains integrity ?

Thanks heaps !!

**Comment by djherbis** [comment]
Hey, I'm a little confused by your question. Just to clarify, are you writing a Go application which will talk to an http server which will store to BoltDB, and you would like to use stow to write Go objects to the http server?

**Comment by joeblew99** [comment]
Neither. Sorry about confusion. Long week and brain dead.

I will use boltdb  and stow in a http server application, where multiple
users will be connecting over http.

So I wanted to know if stow handles the dB connection pooling..

**Comment by djherbis** [comment]
Ah I see, thanks for explaining. BoltDB is a low-level key value store type database. It runs inside the same process as your program (it memory maps a file for storage/persistence) so you don't need to connect to it over a network connection, and doesn't need a concept like connection pooling.

That being said, the database is safe for concurrent use: https://github.com/boltdb/bolt/issues/255
(when used properly)

And stow makes use of a transaction per operation, so every call should have the same guarantees as a boltdb transaction (and be goroutine safe). 

Hope that helps!

**Comment by joeblew99** [comment]
Thanks that's clear. Cheers
