### ISSUE TITLE
No way to find the keys

### ISSUE THREAD

**Issue by fireboy1919** [djherbis/stow#4]
The system is slightly incomplete, as there is no way to iterate over keys with Stow.

The only way to do so is to go back to using the full boltdb interface.

**Comment by djherbis** [comment]
You should be able to accomplish this with:
store.forEach(func(typ *MyType){
  // do something for each stored instance
})

If this doesn't meet your needs, let me know.

**Comment by djherbis** [comment]
If you need to iterate over the values of the keys as well, I'm working on an update which will provide that functionality.

**Comment by fireboy1919** [comment]
Right...there's no way to iterate over the values of the keys.  
This is an especially common use case for an embedded database where you might save all of the configuration data and then fetch all of it out again.

**Comment by djherbis** [comment]
Yeah I see the value in being able to get the keys again. I've got a new release ready which adds support for ForEach which can take take 1 parameter (just the value) or two parameters (key + value).

I'm also adding support for keys of type ([]byte, string, and any type encoded/decoded via the codec).

I have to get permission to push to this project which has taken 7-10 days in the past, sorry for the delay but its a one-time approval so updates can come quicker in the future.

Thanks for your feedback/feature request!

**Comment by djherbis** [comment]
The latest release allows you to do:

store.ForEach(func(key string, value MyType) {
  // do something with key / value.
})

(key may be string, []byte, or any type which can be decoded with the stores Codec.)

Hopefully this fulfills your needs, please let me know if it works for you.

**Comment by fireboy1919** [comment]
That's great!  The naming scheme is a little weird now, since "GetKey" and "PutKey" are obviously *not* for getting or putting keys alone.

Perhaps you should do a version snapshot and re-release the tool to use interfaces rather than building a separate namespace that has exactly the same functions but with a different prefix.

**Comment by djherbis** [comment]
Yeah I agree, I wanted to just replace Get/Put/Pull with the new one, but it technically "breaks" the current api.

I guess I could do a major version bump. I've already snapshotted this version, and the previous version.

Later today I'll move the *Key versions into Get/Put/Pull and do a major version bump.

**Comment by djherbis** [comment]
Pushed the changes and bumped to v2. Let me know if this resolves things for you.

**Comment by fireboy1919** [comment]
Awesome!  That's great.  I'll update to that.
