### ISSUE TITLE
"Get" uses update rather than view

### ISSUE THREAD

**Issue by fireboy1919** [djherbis/stow#5]
The "Get" functionality puts an unnecessary write lock on the boltdb database by calling "Update" rather than "View"

Since this is for embedded applications, this isn't likely to be noticed, but it's something you might want to fix.

**Comment by djherbis** [comment]
Fixed it, that was silly of me. It was because in the original library, Get removed the item from the store (it acted like Pull does now). I guess when I separate those two functions out I didn't switch to using View.

Thanks for the catch, I applied this change to ForEach as well.

**Comment by fireboy1919** [comment]
Great!
