### ISSUE TITLE
Gob encoding is inefficient

### ISSUE THREAD

**Issue by pdf** [djherbis/stow#8]
gob manages to be space efficient on the wire by encoding the structure upfront, and only transmitting it once.  Because stow instantiates a new encoder/decoder for every operation, that efficiency is removed, as type data must be included with every object.  This generally makes gob less space efficient than JSON (I haven't tested the performance aspect).

I don't have an immediate answer to allow persisting gob encodings without type information... it might be possible by creating a pool of encoder/decoder pairs instead of buffers, and priming the decoders by pushing types through at registration time.  Needs some further thought.

**Comment by djherbis** [comment]
Thanks for mentioning this. I am aware that the way I'm using Gob at the moment has a few drawbacks.
If you don't need the type info, then I suggest using one of the other default Codecs, I'd actually be interested in adding a few more efficient codecs to Stow.

That being said, I don't have an exact answer right now on how to make Gob more efficient. I'll try the pooling idea when I get chance, perhaps it will work.

**Comment by pdf** [comment]
Thinking a little more, it may be slightly more complex - there may be a problem if the code desyncs with the stored data, since the type information would no longer be accurate.  Though gob still might be a perf win over JSON, even in its current state.

**Comment by djherbis** [comment]
I think Gob is reasonably robust against changes to the type:
https://golang.org/pkg/encoding/gob/#hdr-Types_and_Values

**Comment by SchumacherFM** [comment]
I've found my working solution for priming gob. A pool cannot be really used in my case because I'm using a bytes.Buffer to save and extract the data, AFAIK same as stow.

Priming is possible for stow but changes of course the API.

Gob is really efficient and can compete with the other encoders :-)

**Comment by djherbis** [comment]
Do you mind sharing your solution? I might be able to add it as a an extension to the API. 

I think I found a way to make it work with pooling (even with byte buffers) awhile ago. I'll see if I can get it going again.

**Comment by djherbis** [comment]
I've added NewPrimedCodec() which lets you pass a Codec and some sample types to Encode to 'prime' the Gob Encoder before it starts writing to the store.

I've also added NewPooledCodec() which will re-use encoders/decoders to help alleviate the extra cost of creating some Encoder/Decoders.

They seem to pass my current tests, if anyone sees any storage gains or has questions/comments I'm happy to hear them.

**Comment by djherbis** [comment]
I haven't tested it myself, but if you wrap GobCodec{} in NewPrimedCodec, you probably need to always use the Primed version of the codec. Otherwise the Encoder/Decoder will expect type information to be stored, and won't find it (written by primed, read by not-primed), or it could find unexpected type information (data written by primed gob, read by non-primed).

**Comment by SchumacherFM** [comment]
Nice idea with the sync.Pool ... but won't work.

I've comment in the commit in the code where I think are the logical challenges

**Comment by djherbis** [comment]
I've replied to your comment, it does work, I think you might be misunderstanding how gob encoding works.

The Pooling will work, as long as your encoder/decoders are state equivalent. For Gob, this means that all of the types that they have encoded/decoded must have been 'first seen' in the same order (this makes their type mapping the same). Priming accomplishes this as long as you don't introduce new types [even as a sub-field of an existing type] when encoding. I'll try to add some more warning comments about these caveats, but I've tested that this does indeed work so long as you follow the usage guidelines carefully (which I'll admit I need to flush out more).

**Comment by SchumacherFM** [comment]
Checked your tests, all is working fine. Great work! Please update the comments in your package.

**Comment by pdf** [comment]
I think it may be possible to avoid most of the caveats by persisting the type descriptions to a 'private' bucket.  Would probably require some reflection to handle the new field type scenario, but it's probably doable, and the overhead would only apply at pool instantiation time.

**Comment by djherbis** [comment]
@SchumacherFM I'll update the comments as soon as I can
@pdf I've considered a number of solutions which involved using a private bucket. Though getting rid of all of the caveats seems rather tricky.

If we have the user pre-select the types that are primed (similar to now), and persist them to a bucket we might protect the user from accidentally re-ordering their types in future builds. However we still wouldn't be able to allow the user to introduce new types when encoding. 

Another option is to try and detect when gob sees a new encoding, and cache that to the private bucket [and re-process the input so that it skips re-printing type info in the regular bucket]. We could then re-process all the cached buckets on every encoder/decoder creation to get them to a consistent state. This would allow new encodings to be auto-included, though it wouldn't play simply with pooling as we'd need to update pool'd encoder/decoder's state whenever new cached types were added.

**Comment by SchumacherFM** [comment]
I ran the numbers with a lot of benchmarks before and after refactoring.

### New Code With Pool encoder/decoder

I've used ideas from your code

```Go
func NewPooledCodec(codec Codecer, types ...interface{}) Codecer {
	return &pooledCodec{
		encoderPool: sync.Pool{New: func() interface{} {
			var enc delegateEncoder
			enc.Encoder = codec.NewEncoder(&enc)
			if len(types) > 0 {
				enc.Writer = ioutil.Discard
				if err := enc.Encode(types); err != nil {
					panic(err)
				}
				enc.Writer = nil
			}
			return &enc
		}},
		decoderPool: sync.Pool{New: func() interface{} {
			var dec delegateDecoder
			dec.Decoder = codec.NewDecoder(&dec)
			if len(types) > 0 {
				var buf = new(bytes.Buffer)
				enc := codec.NewEncoder(buf)
				if err := enc.Encode(types); err != nil {
					panic(err)
				}
				var testTypes []interface{}
				dec.Reader = buf
				if err := dec.Decode(&testTypes); err != nil {
					panic(err)
				}
				dec.Reader = nil
			}
			return &dec
		}},
	}
}
```
Somewhere in my code during a Get() from cache operation:
```Go
	dec := tr.Codec.NewDecoder(buf)
	if pc, ok := tr.Codec.(*pooledCodec); ok {
		defer pc.PutDecoder(dec)
	}
	if err := dec.Decode(dst); err != nil {
		return errors.NewFatal(err, "[transcache] Get.Decode")
	}
```

### Old Code Preinitialized [32]Array

```Go
func WithGobPriming(primeObject interface{}) Option {
	return func(p *Processor) error {

		to := reflect.TypeOf(primeObject)
		encVal := reflect.Zero(to)
		decVal := reflect.New(to)

		for i := 0; i < encodeShards; i++ {
			p.enc[i].Lock()
			p.dec[i].Lock()
			defer p.enc[i].Unlock()
			defer p.dec[i].Unlock()

			enc := p.enc[i].Encoder.(*gob.Encoder)
			dec := p.dec[i].Decoder.(*gob.Decoder)

			if err := enc.EncodeValue(encVal); err != nil {
				return errors.NewFatal(err, " ")
			}
			if _, err := io.Copy(p.dec[i].buf, p.enc[i].buf); err != nil {
				return errors.NewFatal(err, " ")
			}
			p.enc[i].buf.Reset()

			if err := dec.DecodeValue(decVal); err != nil {
				return errors.NewFatal(err, " ")
			}
		}
		return nil
	}
}

func WithEncoder(enc func(io.Writer) Encoder, dec func(io.Reader) Decoder) Option {
	return func(p *Processor) error {
		for i := 0; i < encodeShards; i++ {
			p.enc[i].Encoder = enc(p.enc[i].buf)
			p.dec[i].Decoder = dec(p.dec[i].buf)
		}
		return nil
	}
}

```
Somewhere in my code during a Get() operation

```Go
const encodeShards = 32
type Processor struct {
	Hasher
	Cache Cacher
	enc   [encodeShards]encode
	dec   [encodeShards]decode
}

....... apply options ....

func (tr *Processor) Get(){
	shardID := tr.shardID(key)
	tr.dec[shardID].Lock()
	defer tr.dec[shardID].Unlock()

	if _, err := tr.dec[shardID].buf.Write(val); err != nil {
		return errors.NewWriteFailed(err, " ")
	}
	if err := tr.dec[shardID].Decode(dst); err != nil {
		return errors.NewFatal(err, " ")
	}
}
```

### Results

old with the shards and new with sync.Pool

I've also compared the GcRuntime and of course it is slightly better with pools than the one with the shards. But biggest looser is here MsgPack :-(

```
benchmark                                   old ns/op     new ns/op     delta
Benchmark_BigCache_Country/Gob_1x-4         28494         28393         -0.35%
Benchmark_BigCache_Country/Gob_2x-4         46714         45641         -2.30%
Benchmark_BigCache_Country/JSON_1x-4        70742         60956         -13.83%
Benchmark_BigCache_Country/JSON_2x-4        106144        104381        -1.66%
Benchmark_BigCache_Country/MsgPack_1x-4     23399         26269         +12.27%
Benchmark_BigCache_Country/MsgPack_2x-4     38435         43603         +13.45%
Benchmark_BigCache_Stores/Gob_1x-4          8429          7920          -6.04%
Benchmark_BigCache_Stores/Gob_2x-4          12780         15051         +17.77%
Benchmark_BigCache_Stores/JSON_1x-4         26507         26079         -1.61%
Benchmark_BigCache_Stores/JSON_2x-4         46513         45214         -2.79%
Benchmark_BigCache_Stores/MsgPack_1x-4      14248         15661         +9.92%
Benchmark_BigCache_Stores/MsgPack_2x-4      21758         24280         +11.59%
Benchmark_BoltDB_Gob/Country_1x-4           317097        288149        -9.13%
Benchmark_BoltDB_Gob/Stores_1x-4            251220        258689        +2.97%
Benchmark_Redis_Gob/Country_1x-4            116348        101090        -13.11%
Benchmark_Redis_Gob/Country_2x-4            210698        157953        -25.03%
Benchmark_Redis_Gob/Stores_1x-4             66944         76739         +14.63%
Benchmark_Redis_Gob/Stores_2x-4             101306        102421        +1.10%
Benchmark_Redis_MsgPack/Country_1x-4        87574         95221         +8.73%
Benchmark_Redis_MsgPack/Country_2x-4        138594        151190        +9.09%
Benchmark_Redis_MsgPack/Stores_1x-4         71001         79938         +12.59%
Benchmark_Redis_MsgPack/Stores_2x-4         116169        122617        +5.55%

benchmark                                   old allocs     new allocs     delta
Benchmark_BigCache_Country/Gob_1x-4         429            429            +0.00%
Benchmark_BigCache_Country/Gob_2x-4         747            747            +0.00%
Benchmark_BigCache_Country/JSON_1x-4        418            418            +0.00%
Benchmark_BigCache_Country/JSON_2x-4        706            706            +0.00%
Benchmark_BigCache_Country/MsgPack_1x-4     133            139            +4.51%
Benchmark_BigCache_Country/MsgPack_2x-4     261            270            +3.45%
Benchmark_BigCache_Stores/Gob_1x-4          35             35             +0.00%
Benchmark_BigCache_Stores/Gob_2x-4          64             64             +0.00%
Benchmark_BigCache_Stores/JSON_1x-4         119            119            +0.00%
Benchmark_BigCache_Stores/JSON_2x-4         196            196            +0.00%
Benchmark_BigCache_Stores/MsgPack_1x-4      34             40             +17.65%
Benchmark_BigCache_Stores/MsgPack_2x-4      62             71             +14.52%
Benchmark_BoltDB_Gob/Country_1x-4           491            528            +7.54%
Benchmark_BoltDB_Gob/Stores_1x-4            100            107            +7.00%
Benchmark_Redis_Gob/Country_1x-4            436            458            +5.05%
Benchmark_Redis_Gob/Country_2x-4            758            792            +4.49%
Benchmark_Redis_Gob/Stores_1x-4             42             42             +0.00%
Benchmark_Redis_Gob/Stores_2x-4             75             76             +1.33%
Benchmark_Redis_MsgPack/Country_1x-4        140            146            +4.29%
Benchmark_Redis_MsgPack/Country_2x-4        272            281            +3.31%
Benchmark_Redis_MsgPack/Stores_1x-4         41             47             +14.63%
Benchmark_Redis_MsgPack/Stores_2x-4         73             82             +12.33%

benchmark                                   old bytes     new bytes     delta
Benchmark_BigCache_Country/Gob_1x-4         15730         15742         +0.08%
Benchmark_BigCache_Country/Gob_2x-4         27044         27062         +0.07%
Benchmark_BigCache_Country/JSON_1x-4        14456         14443         -0.09%
Benchmark_BigCache_Country/JSON_2x-4        21457         21430         -0.13%
Benchmark_BigCache_Country/MsgPack_1x-4     5406          10730         +98.48%
Benchmark_BigCache_Country/MsgPack_2x-4     9117          17324         +90.02%
Benchmark_BigCache_Stores/Gob_1x-4          1136          1136          +0.00%
Benchmark_BigCache_Stores/Gob_2x-4          1999          2000          +0.05%
Benchmark_BigCache_Stores/JSON_1x-4         5918          5917          -0.02%
Benchmark_BigCache_Stores/JSON_2x-4         8802          8799          -0.03%
Benchmark_BigCache_Stores/MsgPack_1x-4      1447          6757          +366.97%
Benchmark_BigCache_Stores/MsgPack_2x-4      2247          10453         +365.20%
Benchmark_BoltDB_Gob/Country_1x-4           38979         41232         +5.78%
Benchmark_BoltDB_Gob/Stores_1x-4            17576         17886         +1.76%
Benchmark_Redis_Gob/Country_1x-4            18410         19743         +7.24%
Benchmark_Redis_Gob/Country_2x-4            32226         34271         +6.35%
Benchmark_Redis_Gob/Stores_1x-4             1924          1974          +2.60%
Benchmark_Redis_Gob/Stores_2x-4             3383          3470          +2.57%
Benchmark_Redis_MsgPack/Country_1x-4        9131          14478         +58.56%
Benchmark_Redis_MsgPack/Country_2x-4        16372         24640         +50.50%
Benchmark_Redis_MsgPack/Stores_1x-4         2977          8298          +178.74%
Benchmark_Redis_MsgPack/Stores_2x-4         5121          13338         +160.46%
```
If you want to know more about the code, write me an email or at twitter: same handle

**Comment by djherbis** [comment]
Thanks for adding the benchmarks! I'm not terribly surprised that there was a little slow down here and there. This change was mainly made to reduce # of bits in the stored encoding, so a little performance trade-off isn't bad.
